# Generated by Django 2.2.6 on 2019-12-06 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wazimap', '0014_auto_20191021_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_file', models.FileField(upload_to='datasets/')),
                ('field_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wazimap.FieldTable')),
            ],
        ),
    ]
